services:
  gost-node:
    image: 0xnetuser/gost-node:1.5.3
    container_name: gost-node
    network_mode: host
    restart: unless-stopped
    environment:
      - PANEL_ADDR=http://面板IP:6366
      - SECRET=节点密钥
      - XRAY_ENABLE=false
